---
title: "HURDAT2"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
An R package for accessing NOAA's [HURDAT2 hurricane data]().

### Requirements

 + [R v4.2+](https://www.r-project.org/)
 
 + [rlang](https://CRAN.R-project.org/package=rlang)
 
 + [dplyr](https://CRAN.R-project.org/package=dplyr)
 
 + [readr](https://CRAN.R-project.org/package=readr)
 
 + [sf](https://CRAN.R-project.org/package=sf)
 
 + [ggplot2](https://CRAN.R-project.org/package=ggplot2)
 
 + [colorspace](https://CRAN.R-project.org/package=colorspace)

# Installation

```
remotes::install_github("BigelowLab/hurdat2")
```

# Useage

```{r}
suppressPackageStartupMessages({
  library(sf)
  library(dplyr)
  library(hurdat2)
})
```

Read as POINT data (one obseravtion per row).

```{r}
x = read_hurdat(form = "observations") |>
  glimpse()
```

Read as LINESTRING data (one storm per row)

```{r}
x = read_hurdat(form = "storms") |>
  glimpse()
```

Show a map of the storm track data - grouped by 50-year interval groups.

```{r}
map_hurdat(x, epoch = 50)
```
